# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: entanglement.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x65ntanglement.proto\"o\n\nDefinition\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04\x66ile\x18\x02 \x01(\t\x12\x13\n\x0btarget_file\x18\x03 \x01(\t\x12\x12\n\nattributes\x18\x04 \x01(\t\x12\x1c\n\x14indirect_target_file\x18\x05 \x01(\t\"V\n\x0fLanguageComment\x12\x15\n\ropening_token\x18\x01 \x01(\t\x12\x1a\n\rclosing_token\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\x10\n\x0e_closing_token\";\n\x08Language\x12\x0c\n\x04name\x18\x01 \x01(\t\x12!\n\x07\x63omment\x18\x02 \x01(\x0b\x32\x10.LanguageComment\"<\n\tCodeBlock\x12\x0c\n\x04hash\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\x10\n\x08language\x18\x03 \x01(\t\".\n\tReference\x12\x11\n\treference\x18\x01 \x01(\t\x12\x0e\n\x06indent\x18\x02 \x01(\t\"\x90\x01\n\x0c\x45ntanglement\x12\x19\n\x05\x62lock\x18\x01 \x01(\x0b\x32\n.CodeBlock\x12\x1f\n\ndefinition\x18\x02 \x01(\x0b\x32\x0b.Definition\x12!\n\rreferenced_by\x18\x03 \x03(\x0b\x32\n.Reference\x12!\n\rreferences_to\x18\x04 \x03(\x0b\x32\n.Reference\"9\n\x11\x45ntanglementIndex\x12$\n\rentanglements\x18\x01 \x03(\x0b\x32\r.Entanglementb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'entanglement_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DEFINITION._serialized_start=22
  _DEFINITION._serialized_end=133
  _LANGUAGECOMMENT._serialized_start=135
  _LANGUAGECOMMENT._serialized_end=221
  _LANGUAGE._serialized_start=223
  _LANGUAGE._serialized_end=282
  _CODEBLOCK._serialized_start=284
  _CODEBLOCK._serialized_end=344
  _REFERENCE._serialized_start=346
  _REFERENCE._serialized_end=392
  _ENTANGLEMENT._serialized_start=395
  _ENTANGLEMENT._serialized_end=539
  _ENTANGLEMENTINDEX._serialized_start=541
  _ENTANGLEMENTINDEX._serialized_end=598
# @@protoc_insertion_point(module_scope)
