# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: staging.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rstaging.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"@\n\rCreationInput\x12\x15\n\rnew_file_name\x18\x01 \x01(\t\x12\x18\n\x10new_file_content\x18\x02 \x01(\t\"\"\n\rDeletionInput\x12\x11\n\tfile_name\x18\x01 \x01(\t\"?\n\x0bUpdateInput\x12\x1a\n\x12\x65xisting_file_name\x18\x01 \x01(\t\x12\x14\n\x0c\x64iff_content\x18\x02 \x01(\t\"\xab\x01\n\x0c\x43hangeRecord\x12\x19\n\x04type\x18\x01 \x01(\x0e\x32\x0b.ChangeType\x12%\n\x0b\x63reate_data\x18\x04 \x01(\x0b\x32\x0e.CreationInputH\x00\x12%\n\x0b\x64\x65lete_data\x18\x05 \x01(\x0b\x32\x0e.DeletionInputH\x00\x12#\n\x0bupdate_data\x18\x06 \x01(\x0b\x32\x0c.UpdateInputH\x00\x42\r\n\x0b\x63hange_data\"T\n\x0e\x43hangeRecordId\x12\x0c\n\x04hash\x18\x01 \x01(\t\x12\x34\n\x10preparation_time\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\x93\x01\n\rChangeRecords\x12\x1b\n\x02id\x18\x01 \x01(\x0b\x32\x0f.ChangeRecordId\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x1e\n\x07records\x18\x03 \x03(\x0b\x32\r.ChangeRecord\x12\x16\n\x0e\x66iles_to_index\x18\x04 \x03(\t\x12\x18\n\x10\x66iles_to_unindex\x18\x05 \x03(\t\"+\n\x0b\x43hangeIndex\x12\x1c\n\x03ids\x18\x01 \x03(\x0b\x32\x0f.ChangeRecordId*0\n\nChangeType\x12\n\n\x06\x43REATE\x10\x00\x12\n\n\x06\x44\x45LETE\x10\x01\x12\n\n\x06UPDATE\x10\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'staging_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CHANGETYPE._serialized_start=672
  _CHANGETYPE._serialized_end=720
  _CREATIONINPUT._serialized_start=50
  _CREATIONINPUT._serialized_end=114
  _DELETIONINPUT._serialized_start=116
  _DELETIONINPUT._serialized_end=150
  _UPDATEINPUT._serialized_start=152
  _UPDATEINPUT._serialized_end=215
  _CHANGERECORD._serialized_start=218
  _CHANGERECORD._serialized_end=389
  _CHANGERECORDID._serialized_start=391
  _CHANGERECORDID._serialized_end=475
  _CHANGERECORDS._serialized_start=478
  _CHANGERECORDS._serialized_end=625
  _CHANGEINDEX._serialized_start=627
  _CHANGEINDEX._serialized_end=670
# @@protoc_insertion_point(module_scope)
